version: '3.8'
services:
  dspa-app:
    container_name: dspa_app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - dspa-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 